namespace Enum
{
    public enum TutorialTextPart
    {
        StartMonologue,
        HelpFolderOneP1,
        HelpFolderOneP2,
        HelpFolderTwo,
        HelpFolderThree,
        HelpFolderEndP1,
        HelpFolderEndP2,
        EmailOne,
        InboxWalkThroughP1,
        InboxWalkThroughP2,
        InboxWalkThroughP3,
        InboxWalkThroughP4,
        InboxWalkThroughP5,
        InboxWalkThroughP6,
        EmailThreeP1,
        EmailThreeP2,
        PrintCaseP1,
        PrintCaseP2,
        SolveCaseOneP1,
        SolveCaseOneP2,
        SolveCaseTwo,
        TutorialWin,
        TutorialLose
    }
}
